tap "fujiwara/tap"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "kayac/tap"
tap "knqyf263/utern"
tap "minamijoyo/tfschema"

brew "anyenv"
brew "awscli"
brew "bat"
brew "ccat"
brew "colordiff"
brew "ctop"
brew "curl"
brew "direnv"
brew "docker-compose"
brew "duf"
brew "expect" # unbuffer に必要 https://dev.classmethod.jp/articles/fzf-original-app-for-git-add/
brew "fd"
brew "fujiwara/tap/aswrap"
brew "fujiwara/tap/ecsta"
brew "fujiwara/tap/lambroll"
brew "fzf"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-delta"
brew "git-secrets"
brew "gnumeric" # ssconvert に必要
brew "grep"
brew "htop"
brew "imagemagick"
brew "jq"
brew "kayac/tap/ecspresso"
brew "knqyf263/utern/utern"
brew "lazydocker"
brew "mas"
brew "minamijoyo/tfschema/tfschema"
brew "ripgrep"
brew "sheldon"
brew "sops"
brew "starship"
# brew "synergy" 3系がstableになるまで手動
brew "terminal-notifier"
brew "tflint"
brew "tig"
brew "tmux"
brew "trash"
brew "tree"
brew "wget"
brew "zsh"

cask "1password"
cask "appcleaner"
cask "authy"
cask "cheatsheet"
cask "cyberduck"
cask "deepl"
cask "discord"
cask "docker"
cask "dropbox"
cask "flux"
cask "font-ricty-diminished"
cask "fuwari"
cask "google-chrome"
cask "google-drive"
cask "google-japanese-ime"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keepassx"
cask "kindle"
cask "microsoft-edge"
cask "mysqlworkbench"
cask "parallels"
cask "raycast"
cask "session-manager-plugin"
cask "skitch"
cask "slack"
cask "snes9x"
cask "stoplight-studio"
cask "the-unarchiver"
cask "tradingview"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

mas "Amphetamine", id: 937984704
mas "Display Maid", id: 450063525
mas "Divvy", id: 413857545
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "Pages", id: 409201541
mas "Paste Plain Text", id: 1407015686
mas "ScreenNote", id: 1258500140
mas "VirusBarrier Scanner", id: 1200445649
mas "Xcode", id: 497799835
mas "grsyncx", id: 1506997025

vscode "JeylaniB.pinescript"
vscode "MS-CEINTL.vscode-language-pack-ja"
