shell = 'zsh'

[plugins]

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-autocomplete]
github = 'marlonrichert/zsh-autocomplete'

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.enhancd]
github = 'babarot/enhancd'
use = ['init.sh']

[plugins.asdf]
github = 'asdf-vm/asdf'

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
