"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[%](bold)"
error_symbol = "[%](#CC6666 bold)"

[directory]
style = '#81A2BE bold'
truncation_length = 100
truncate_to_repo = false

[git_branch]
style = '#B294BB bold'
format = "[$branch(:$remote_branch)]($style) "
truncation_length = 100

[git_status]
format = '$all_status$ahead_behind '
conflicted = '[=](#CC6666 bold) '
ahead = '[⇡](#B5BD68 bold) '
behind = '[⇣](#B5BD68 bold) '
diverged = '[⇕](#B5BD68 bold) '
up_to_date = '[✓](#8ABEB7 bold) '
untracked = '[?](#DE935F bold) '
stashed = '[\$](#CC6666 bold) '
modified = '[!](#DE935F bold) '
staged = '[+](#B5BD68 bold) '
renamed = '[»](#DE935F bold) '
deleted = '[✘](#DE935F bold) '

[aws]
disabled = true

[battery]
disabled = true

[docker_context]
disabled = true

[golang]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[terraform]
disabled = true
