"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 1000

format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[%](bold)"
error_symbol = "[%](#CC6666 bold)"

[directory]
format = '[$path]($style) [$read_only]($read_only_style)'
style = '#81A2BE bold'
read_only = 'read only'
read_only_style = '#CC6666 bold'
truncation_length = 100
truncate_to_repo = false

[git_branch]
style = '#B294BB bold'
format = "[$branch(:$remote_branch)]($style) "
truncation_length = 100

[git_status]
format = '$all_status$ahead_behind '
conflicted = '[=](#CC6666 bold) '
ahead = '[⇡](#B5BD68 bold) '
behind = '[⇣](#B5BD68 bold) '
diverged = '[⇕](#B5BD68 bold) '
up_to_date = '[✓](#8ABEB7 bold) '
untracked = '[?](#DE935F bold) '
stashed = '[\$](#CC6666 bold) '
modified = '[!](#DE935F bold) '
staged = '[+](#B5BD68 bold) '
renamed = '[»](#DE935F bold) '
deleted = '[✘](#DE935F bold) '
